// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/enroll/v1/enroll.proto

package enrollv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnrollmentService_Claim_FullMethodName  = "/pigeon.enroll.v1.EnrollmentService/Claim"
	EnrollmentService_Render_FullMethodName = "/pigeon.enroll.v1.EnrollmentService/Render"
)

// EnrollmentServiceClient is the client API for EnrollmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EnrollmentService provides secret enrollment via HMAC token authentication
// with optional TPM attestation.
//
// Follows the SPIRE AttestAgent bidirectional stream pattern:
// - TPM: params → challenge → challenge_response → result
// - Token-only: params → result
type EnrollmentServiceClient interface {
	Claim(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClaimRequest, ClaimResponse], error)
	// Render returns a server-rendered template with fresh credentials embedded.
	// Templates are defined in the server config via "template" blocks.
	// The caller authenticates via mTLS (same as Claim).
	Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error)
}

type enrollmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnrollmentServiceClient(cc grpc.ClientConnInterface) EnrollmentServiceClient {
	return &enrollmentServiceClient{cc}
}

func (c *enrollmentServiceClient) Claim(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClaimRequest, ClaimResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EnrollmentService_ServiceDesc.Streams[0], EnrollmentService_Claim_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClaimRequest, ClaimResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EnrollmentService_ClaimClient = grpc.BidiStreamingClient[ClaimRequest, ClaimResponse]

func (c *enrollmentServiceClient) Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderResponse)
	err := c.cc.Invoke(ctx, EnrollmentService_Render_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnrollmentServiceServer is the server API for EnrollmentService service.
// All implementations must embed UnimplementedEnrollmentServiceServer
// for forward compatibility.
//
// EnrollmentService provides secret enrollment via HMAC token authentication
// with optional TPM attestation.
//
// Follows the SPIRE AttestAgent bidirectional stream pattern:
// - TPM: params → challenge → challenge_response → result
// - Token-only: params → result
type EnrollmentServiceServer interface {
	Claim(grpc.BidiStreamingServer[ClaimRequest, ClaimResponse]) error
	// Render returns a server-rendered template with fresh credentials embedded.
	// Templates are defined in the server config via "template" blocks.
	// The caller authenticates via mTLS (same as Claim).
	Render(context.Context, *RenderRequest) (*RenderResponse, error)
	mustEmbedUnimplementedEnrollmentServiceServer()
}

// UnimplementedEnrollmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnrollmentServiceServer struct{}

func (UnimplementedEnrollmentServiceServer) Claim(grpc.BidiStreamingServer[ClaimRequest, ClaimResponse]) error {
	return status.Error(codes.Unimplemented, "method Claim not implemented")
}
func (UnimplementedEnrollmentServiceServer) Render(context.Context, *RenderRequest) (*RenderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Render not implemented")
}
func (UnimplementedEnrollmentServiceServer) mustEmbedUnimplementedEnrollmentServiceServer() {}
func (UnimplementedEnrollmentServiceServer) testEmbeddedByValue()                           {}

// UnsafeEnrollmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnrollmentServiceServer will
// result in compilation errors.
type UnsafeEnrollmentServiceServer interface {
	mustEmbedUnimplementedEnrollmentServiceServer()
}

func RegisterEnrollmentServiceServer(s grpc.ServiceRegistrar, srv EnrollmentServiceServer) {
	// If the following call panics, it indicates UnimplementedEnrollmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnrollmentService_ServiceDesc, srv)
}

func _EnrollmentService_Claim_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EnrollmentServiceServer).Claim(&grpc.GenericServerStream[ClaimRequest, ClaimResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EnrollmentService_ClaimServer = grpc.BidiStreamingServer[ClaimRequest, ClaimResponse]

func _EnrollmentService_Render_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).Render(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_Render_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).Render(ctx, req.(*RenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnrollmentService_ServiceDesc is the grpc.ServiceDesc for EnrollmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnrollmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pigeon.enroll.v1.EnrollmentService",
	HandlerType: (*EnrollmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Render",
			Handler:    _EnrollmentService_Render_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Claim",
			Handler:       _EnrollmentService_Claim_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/enroll/v1/enroll.proto",
}
